version: "3.9"
services:
  analysis:
      image: jupyter/scipy-notebook
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/milestones
      environment:
        - JUPYTER_ENABLE_LAB=yes

# version: "3.9"
# services:
#   analysis:
#       build: .
#       volumes:
#         - .:/home/jovyan/milestones
#       stdin_open: true # docker run -i
#       tty: true        # docker run -t